### ISSUE TITLE
Bool func

### ISSUE THREAD

**Issue by AMBIENTE1** [samiyr/SwiftyPing#30]
Hello Samiyr,

thank you for your project, nice work! I would like to ask how is best way to write a Boll func which checks if the ping is OK or NOT? Exist someone variable witch this result?
I try this:

` func test () -> Bool {
        
        var ping: Bool = false
        
        let once = try? SwiftyPing(host: "38.8.8.8", configuration: PingConfiguration(interval: 0.2, with: 1), queue: DispatchQueue.global())
        once?.observer = { (response) in
            let err = response.error
            if err == nil { ping = true }
            print (err)
            
        }
        
        once?.targetCount = 1
        try? once?.startPinging()
       
      print (ping)          //there is probleb because ping is still false
      return ping
        
        
        
}
`

Carlos

**Comment by samiyr** [comment]
The problem here is that you're trying to return synchronously from an async method. `test()` will return immediately, while sending and receiving the ping will take some time. `return ping` will be (most likely) called before the ping is even sent, so the `observer` is never called. This is a common problem and the two usual solutions are to either convert the function `test()` to an async function or to wait for `observer` to be called. Converting `test()` to an async function could look something like this:

```swift
func test(completion: @escaping (Bool) -> ()) {
    let once = try? SwiftyPing(host: "38.8.8.8", configuration: PingConfiguration(interval: 0.2, with: 1), queue: DispatchQueue.global())
    once?.observer = { (response) in
        let err = response.error
        let ping = err == nil
        completion(ping)
    }
        
    once?.targetCount = 1
    try? once?.startPinging()
}
```

Calling this function now looks like

```swift
test { result in
    print(result)
}
```

If you need `test()` to be a sync function (maybe down the line you need the result immediately and Swift's async/await capability isn't here yet), you need to somehow wait before calling `return ping`. There are many ways to do this, e.g. `DispatchSemaphore` or `DispatchGroup`, see [this](https://stackoverflow.com/questions/42484281/waiting-until-the-task-finishes) for instance.

**Comment by AMBIENTE1** [comment]
Thank you very much! ;-)
